apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutualfund
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutualfund
  template:
    metadata:
      labels:
        app: mutualfund
    spec:
      containers:
      - name: mutualfund
        image: pmscontainerreg.azurecr.io/mutualfundsimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvssecret

---
apiVersion: v1
kind: Service
metadata:
  name: mutualfund-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mutualfund